/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.hobbytracker.panels;

/**
 *
 * @author moises theo
 */
public class habit extends javax.swing.JPanel {

    /**
     * Creates new form habit
     */
    public habit() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setLayout(null);

        jLabel1.setText("image");
        add(jLabel1);
        jLabel1.setBounds(6, 27, 33, 16);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Drink water");
        add(jLabel2);
        jLabel2.setBounds(57, 6, 125, 20);

        jLabel3.setForeground(new java.awt.Color(204, 204, 204));
        jLabel3.setText("0/1000mL");
        add(jLabel3);
        jLabel3.setBounds(57, 31, 125, 16);

        jButton1.setText("Log");
        add(jButton1);
        jButton1.setBounds(429, 24, 90, 23);

        jButton2.setText("jButton1");
        add(jButton2);
        jButton2.setBounds(531, 24, 36, 23);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
